spring:
  application:
    name: demande-service
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:8888"
  data:
    mongodb:
      uri: "mongodb://${MONGO_HOST:mongodb}:27017/demande_db"

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_HOST:eureka-server}:8761/eureka/"
